version: '3'
services:
  mongo:
    container_name: mongo
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    ports:
     - "49160:8080"
    command: npm start
    links:
     - "mongo"
  