version: '3'
services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: app
    build: .
    ports:
     - "49160:8080"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    command: npm run start
    links:
     - "mongodb"
  